# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Stadium Name')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='stadium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.Stadium'),
            preserve_default=False,
        ),
    ]
