# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20160604_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Capacity'),
        ),
    ]
