# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='attendance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Attendance'),
        ),
        migrations.AddField(
            model_name='game',
            name='awayTeam',
            field=models.ForeignKey(default=-9999, on_delete=django.db.models.deletion.CASCADE, related_name='awayTeam', to='games.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='homeTeam',
            field=models.ForeignKey(default=-9999, on_delete=django.db.models.deletion.CASCADE, related_name='homeTeam', to='games.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Stadium'),
        ),
    ]
