# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20160605_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='city',
            field=models.CharField(default='', max_length=200, verbose_name='Stadium City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadium',
            name='is_primary',
            field=models.BooleanField(default=True, verbose_name='Regular MLS stadium'),
        ),
        migrations.AddField(
            model_name='stadium',
            name='soccer_specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stadium',
            name='state',
            field=models.CharField(default='', max_length=200, verbose_name='Stadium State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadium',
            name='surface',
            field=models.CharField(choices=[('1', 'Grass'), ('2', 'AstroTurf'), ('3', 'FieldTurf'), ('4', 'Turf'), ('5', 'Bluegrass'), ('6', 'Polytan'), ('7', 'Team Pro EF RD'), ('8', 'AstroTurf GameDay Grass 3D'), ('9', 'Bermuda Bandera / Ryegrass Mixture')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='stadium',
            name='sw_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadium',
            name='year_opened',
            field=models.IntegerField(default=-9999),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Soccer-specific capacity'),
        ),
    ]
