# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20160605_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Stadium'),
        ),
    ]
