# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20160605_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='yearJoined',
        ),
        migrations.AddField(
            model_name='team',
            name='sw_id',
            field=models.IntegerField(default=-9999, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='year_joined',
            field=models.IntegerField(default=-9999, verbose_name='yearJoined'),
        ),
        migrations.AlterField(
            model_name='team',
            name='conference',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Conference'),
        ),
    ]
