# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20160613_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='sw_id',
            field=models.IntegerField(unique=True),
        ),
    ]
