# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20160613_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='sw_id',
        ),
    ]
