# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_remove_team_year_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sw_id',
            field=models.IntegerField(default=-1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='year_joined',
            field=models.IntegerField(default=-9999, verbose_name='yearJoined'),
        ),
    ]
