# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20160617_2002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('homeTeam', 'awayTeam', 'date')]),
        ),
    ]
