# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_auto_20160704_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(default=-9999, on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='games.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(default=-9999, on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='games.Team'),
        ),
    ]
