# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20160704_0033'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('half', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('seconds', models.FloatField(default=0.0)),
                ('action', models.CharField(choices=[('BLOCK', 'Block'), ('CLEARANCE', 'Clearance'), ('CORNER_CROSS', 'Corner Cross'), ('CROSS', 'Cross'), ('DEFLECTION', 'Deflection'), ('DIRECT_FREE_KICK_CROSS', 'Direct Free Kick Cross'), ('DIRECT_FREE_KICK_PASS', 'Direct Free Kick Pass'), ('DIRECT_FREE_KICK_SHOT', 'Direct Free Kick Shot'), ('DRIBBLE', 'Dribble'), ('DROP_BALL', 'Drop Ball'), ('FOUL', 'Foul'), ('FOUL_THROW', 'Foul Throw'), ('GOAL', 'Goal'), ('GOAL_KICK', 'Goal Kick'), ('GOALKEEPER_CATCH', 'Goalkeeper Catch'), ('GOALKEEPER_DROP_CATCH', 'Goalkeeper Drop Catch'), ('GOALKEEPER_KICK', 'Goalkeeper Kick'), ('GOALKEEPER_PICK_UP', 'Goalkeeper Pick Up'), ('GOALKEEPER_PUNCH', 'Goalkeeper Punch'), ('GOALKEEPER_SAVE', 'Goalkeeper Save'), ('GOALKEEPER_SAVE_CATCH', 'Goalkeeper Save Catch'), ('GOALKEEPER_THROW', 'Goalkeeper Throw'), ('HANDBALL', 'Handball'), ('HEADER', 'Header'), ('HEADER_SHOT', 'Header Shot'), ('INDIRECT_FREE_KICK_CROSS', 'Indirect Free Kick Cross'), ('INDIRECT_FREE_KICK_PASS', 'Indirect Free Kick Pass'), ('KICK_OFF', 'Kick Off'), ('OFFSIDE', 'Offside'), ('OWN_GOAL', 'Own Goal'), ('PASS', 'Pass'), ('PENALTY_SHOT', 'Penalty Shot'), ('RED_CARD', 'Red Card'), ('SHOT', 'Shot'), ('START_HALF', 'Start Half'), ('SUBSTITUTION', 'Substitution'), ('TACKLE', 'Tackle'), ('THROWN_IN', 'Thrown In'), ('TOUCH', 'Touch'), ('YELLOW_CARD', 'Yellow Card')], default='PASS', max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='disciplinaryaction',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='minute',
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='half',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='seconds',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='goal',
            name='half',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
        migrations.AddField(
            model_name='goal',
            name='seconds',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='substitution',
            name='half',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
        migrations.AddField(
            model_name='substitution',
            name='seconds',
            field=models.FloatField(default=0.0),
        ),
    ]
