# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20160704_0033'),
        ('events', '0004_auto_20160714_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticevent',
            name='action_team',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='actions', to='games.Team'),
        ),
    ]
