# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20160704_0033'),
        ('events', '0005_statisticevent_action_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_on_pitch', models.FloatField()),
                ('minute', models.IntegerField()),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('passes', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Team')),
            ],
        ),
    ]
