# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20160720_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeevent',
            old_name='first_time_complete',
            new_name='first_time_passes_complete',
        ),
        migrations.RenameField(
            model_name='timeevent',
            old_name='first_time_incomplete',
            new_name='first_time_passes_incomplete',
        ),
    ]
