# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20160720_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinaryaction',
            name='game',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='game',
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='game',
        ),
        migrations.DeleteModel(
            name='DisciplinaryAction',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Substitution',
        ),
    ]
